services:
  mysql:
    image: "mysql:8.0.43-debian"
    environment:
      MYSQL_DATABASE: full_stack_ecommerce
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    cap_add:
      - SYS_NICE
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: vacation_booking_api
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped


volumes:
  mysql-data: